// Code generated by sqlc-grpc (https://github.com/walterwanderley/sqlc-grpc).

package pguuid

import (
	"github.com/jackc/pgx/v5/pgxpool"

	pb "uuidcheck/api/pguuid/v1"
)

// NewService is a constructor of a pb.PguuidServiceServer implementation.
// Use this function to customize the server by adding middlewares to it.
func NewService(querier *Queries, db *pgxpool.Pool) pb.PguuidServiceServer {
	return &Service{querier: querier}
}
