// Code generated by sqlc-grpc (https://github.com/walterwanderley/sqlc-grpc). DO NOT EDIT.

package authors

import (
	"google.golang.org/protobuf/types/known/wrapperspb"

	pb "booktest/api/authors/v1"
)

func toAuthor(in Author) *pb.Author {

	out := new(pb.Author)
	out.Id = in.ID
	out.Name = in.Name
	if in.Bio.Valid {
		out.Bio = wrapperspb.String(in.Bio.String)
	}
	return out
}
