// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package authors

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Authors struct {
	ID        int64            `json:"id"`
	Name      string           `json:"name"`
	Bio       pgtype.Text      `json:"bio"`
	Age       pgtype.Numeric   `json:"age"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
