// Code generated by sqlc-grpc (https://github.com/walterwanderley/sqlc-grpc). DO NOT EDIT.

package authors

import (
	"context"
	"database/sql"
	"log/slog"

	pb "authors/api/authors/v1"
)

type Service struct {
	pb.UnimplementedAuthorsServiceServer
	querier *Queries
}

func (s *Service) CreateAuthor(ctx context.Context, req *pb.CreateAuthorRequest) (*pb.CreateAuthorResponse, error) {
	var arg CreateAuthorParams
	arg.Name = req.GetName()
	if v := req.GetBio(); v != nil {
		arg.Bio = sql.NullString{Valid: true, String: v.Value}
	}

	result, err := s.querier.CreateAuthor(ctx, arg)
	if err != nil {
		slog.Error("CreateAuthor sql call failed", "error", err)
		return nil, err
	}
	return &pb.CreateAuthorResponse{Value: toExecResult(result)}, nil
}

func (s *Service) DeleteAuthor(ctx context.Context, req *pb.DeleteAuthorRequest) (*pb.DeleteAuthorResponse, error) {
	id := req.GetId()

	err := s.querier.DeleteAuthor(ctx, id)
	if err != nil {
		slog.Error("DeleteAuthor sql call failed", "error", err)
		return nil, err
	}
	return &pb.DeleteAuthorResponse{}, nil
}

func (s *Service) GetAuthor(ctx context.Context, req *pb.GetAuthorRequest) (*pb.GetAuthorResponse, error) {
	id := req.GetId()

	result, err := s.querier.GetAuthor(ctx, id)
	if err != nil {
		slog.Error("GetAuthor sql call failed", "error", err)
		return nil, err
	}
	return &pb.GetAuthorResponse{Author: toAuthor(result)}, nil
}

func (s *Service) ListAuthors(ctx context.Context, req *pb.ListAuthorsRequest) (*pb.ListAuthorsResponse, error) {

	result, err := s.querier.ListAuthors(ctx)
	if err != nil {
		slog.Error("ListAuthors sql call failed", "error", err)
		return nil, err
	}
	res := new(pb.ListAuthorsResponse)
	for _, r := range result {
		res.List = append(res.List, toAuthor(r))
	}
	return res, nil
}

func (s *Service) WithTx(tx *sql.Tx) *Service {
	return &Service{
		querier: s.querier.WithTx(tx),
	}
}
