// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: pguuid/v1/pguuid.proto

/*
Package v1 is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package v1

import (
	"context"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray
var _ = metadata.Join

func request_PguuidService_CreateProduct_0(ctx context.Context, marshaler runtime.Marshaler, client PguuidServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq CreateProductRequest
	var metadata runtime.ServerMetadata

	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.CreateProduct(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_PguuidService_CreateProduct_0(ctx context.Context, marshaler runtime.Marshaler, server PguuidServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq CreateProductRequest
	var metadata runtime.ServerMetadata

	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.CreateProduct(ctx, &protoReq)
	return msg, metadata, err

}

func request_PguuidService_CreateProductReturnAll_0(ctx context.Context, marshaler runtime.Marshaler, client PguuidServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq CreateProductReturnAllRequest
	var metadata runtime.ServerMetadata

	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.CreateProductReturnAll(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_PguuidService_CreateProductReturnAll_0(ctx context.Context, marshaler runtime.Marshaler, server PguuidServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq CreateProductReturnAllRequest
	var metadata runtime.ServerMetadata

	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.CreateProductReturnAll(ctx, &protoReq)
	return msg, metadata, err

}

func request_PguuidService_CreateProductReturnPartial_0(ctx context.Context, marshaler runtime.Marshaler, client PguuidServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq CreateProductReturnPartialRequest
	var metadata runtime.ServerMetadata

	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.CreateProductReturnPartial(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_PguuidService_CreateProductReturnPartial_0(ctx context.Context, marshaler runtime.Marshaler, server PguuidServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq CreateProductReturnPartialRequest
	var metadata runtime.ServerMetadata

	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.CreateProductReturnPartial(ctx, &protoReq)
	return msg, metadata, err

}

func request_PguuidService_CreateUser_0(ctx context.Context, marshaler runtime.Marshaler, client PguuidServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq CreateUserRequest
	var metadata runtime.ServerMetadata

	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.CreateUser(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_PguuidService_CreateUser_0(ctx context.Context, marshaler runtime.Marshaler, server PguuidServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq CreateUserRequest
	var metadata runtime.ServerMetadata

	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.CreateUser(ctx, &protoReq)
	return msg, metadata, err

}

func request_PguuidService_CreateUserReturnAll_0(ctx context.Context, marshaler runtime.Marshaler, client PguuidServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq CreateUserReturnAllRequest
	var metadata runtime.ServerMetadata

	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.CreateUserReturnAll(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_PguuidService_CreateUserReturnAll_0(ctx context.Context, marshaler runtime.Marshaler, server PguuidServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq CreateUserReturnAllRequest
	var metadata runtime.ServerMetadata

	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.CreateUserReturnAll(ctx, &protoReq)
	return msg, metadata, err

}

func request_PguuidService_CreateUserReturnPartial_0(ctx context.Context, marshaler runtime.Marshaler, client PguuidServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq CreateUserReturnPartialRequest
	var metadata runtime.ServerMetadata

	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.CreateUserReturnPartial(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_PguuidService_CreateUserReturnPartial_0(ctx context.Context, marshaler runtime.Marshaler, server PguuidServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq CreateUserReturnPartialRequest
	var metadata runtime.ServerMetadata

	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.CreateUserReturnPartial(ctx, &protoReq)
	return msg, metadata, err

}

// RegisterPguuidServiceHandlerServer registers the http handlers for service PguuidService to "mux".
// UnaryRPC     :call PguuidServiceServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterPguuidServiceHandlerFromEndpoint instead.
// GRPC interceptors will not work for this type of registration. To use interceptors, you must use the "runtime.WithMiddlewares" option in the "runtime.NewServeMux" call.
func RegisterPguuidServiceHandlerServer(ctx context.Context, mux *runtime.ServeMux, server PguuidServiceServer) error {

	mux.Handle("POST", pattern_PguuidService_CreateProduct_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/pguuid.v1.PguuidService/CreateProduct", runtime.WithHTTPPathPattern("/product"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_PguuidService_CreateProduct_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_PguuidService_CreateProduct_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("POST", pattern_PguuidService_CreateProductReturnAll_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/pguuid.v1.PguuidService/CreateProductReturnAll", runtime.WithHTTPPathPattern("/product-return-all"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_PguuidService_CreateProductReturnAll_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_PguuidService_CreateProductReturnAll_0(annotatedContext, mux, outboundMarshaler, w, req, response_PguuidService_CreateProductReturnAll_0{resp.(*CreateProductReturnAllResponse)}, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("POST", pattern_PguuidService_CreateProductReturnPartial_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/pguuid.v1.PguuidService/CreateProductReturnPartial", runtime.WithHTTPPathPattern("/product-return-partial"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_PguuidService_CreateProductReturnPartial_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_PguuidService_CreateProductReturnPartial_0(annotatedContext, mux, outboundMarshaler, w, req, response_PguuidService_CreateProductReturnPartial_0{resp.(*CreateProductReturnPartialResponse)}, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("POST", pattern_PguuidService_CreateUser_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/pguuid.v1.PguuidService/CreateUser", runtime.WithHTTPPathPattern("/user"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_PguuidService_CreateUser_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_PguuidService_CreateUser_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("POST", pattern_PguuidService_CreateUserReturnAll_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/pguuid.v1.PguuidService/CreateUserReturnAll", runtime.WithHTTPPathPattern("/user-return-all"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_PguuidService_CreateUserReturnAll_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_PguuidService_CreateUserReturnAll_0(annotatedContext, mux, outboundMarshaler, w, req, response_PguuidService_CreateUserReturnAll_0{resp.(*CreateUserReturnAllResponse)}, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("POST", pattern_PguuidService_CreateUserReturnPartial_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/pguuid.v1.PguuidService/CreateUserReturnPartial", runtime.WithHTTPPathPattern("/user-return-partial"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_PguuidService_CreateUserReturnPartial_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_PguuidService_CreateUserReturnPartial_0(annotatedContext, mux, outboundMarshaler, w, req, response_PguuidService_CreateUserReturnPartial_0{resp.(*CreateUserReturnPartialResponse)}, mux.GetForwardResponseOptions()...)

	})

	return nil
}

// RegisterPguuidServiceHandlerFromEndpoint is same as RegisterPguuidServiceHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterPguuidServiceHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.NewClient(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Errorf("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Errorf("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterPguuidServiceHandler(ctx, mux, conn)
}

// RegisterPguuidServiceHandler registers the http handlers for service PguuidService to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterPguuidServiceHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterPguuidServiceHandlerClient(ctx, mux, NewPguuidServiceClient(conn))
}

// RegisterPguuidServiceHandlerClient registers the http handlers for service PguuidService
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "PguuidServiceClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "PguuidServiceClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "PguuidServiceClient" to call the correct interceptors. This client ignores the HTTP middlewares.
func RegisterPguuidServiceHandlerClient(ctx context.Context, mux *runtime.ServeMux, client PguuidServiceClient) error {

	mux.Handle("POST", pattern_PguuidService_CreateProduct_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/pguuid.v1.PguuidService/CreateProduct", runtime.WithHTTPPathPattern("/product"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_PguuidService_CreateProduct_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_PguuidService_CreateProduct_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("POST", pattern_PguuidService_CreateProductReturnAll_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/pguuid.v1.PguuidService/CreateProductReturnAll", runtime.WithHTTPPathPattern("/product-return-all"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_PguuidService_CreateProductReturnAll_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_PguuidService_CreateProductReturnAll_0(annotatedContext, mux, outboundMarshaler, w, req, response_PguuidService_CreateProductReturnAll_0{resp.(*CreateProductReturnAllResponse)}, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("POST", pattern_PguuidService_CreateProductReturnPartial_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/pguuid.v1.PguuidService/CreateProductReturnPartial", runtime.WithHTTPPathPattern("/product-return-partial"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_PguuidService_CreateProductReturnPartial_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_PguuidService_CreateProductReturnPartial_0(annotatedContext, mux, outboundMarshaler, w, req, response_PguuidService_CreateProductReturnPartial_0{resp.(*CreateProductReturnPartialResponse)}, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("POST", pattern_PguuidService_CreateUser_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/pguuid.v1.PguuidService/CreateUser", runtime.WithHTTPPathPattern("/user"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_PguuidService_CreateUser_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_PguuidService_CreateUser_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("POST", pattern_PguuidService_CreateUserReturnAll_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/pguuid.v1.PguuidService/CreateUserReturnAll", runtime.WithHTTPPathPattern("/user-return-all"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_PguuidService_CreateUserReturnAll_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_PguuidService_CreateUserReturnAll_0(annotatedContext, mux, outboundMarshaler, w, req, response_PguuidService_CreateUserReturnAll_0{resp.(*CreateUserReturnAllResponse)}, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("POST", pattern_PguuidService_CreateUserReturnPartial_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/pguuid.v1.PguuidService/CreateUserReturnPartial", runtime.WithHTTPPathPattern("/user-return-partial"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_PguuidService_CreateUserReturnPartial_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_PguuidService_CreateUserReturnPartial_0(annotatedContext, mux, outboundMarshaler, w, req, response_PguuidService_CreateUserReturnPartial_0{resp.(*CreateUserReturnPartialResponse)}, mux.GetForwardResponseOptions()...)

	})

	return nil
}

type response_PguuidService_CreateProductReturnAll_0 struct {
	*CreateProductReturnAllResponse
}

func (m response_PguuidService_CreateProductReturnAll_0) XXX_ResponseBody() interface{} {
	return m.Product
}

type response_PguuidService_CreateProductReturnPartial_0 struct {
	*CreateProductReturnPartialResponse
}

func (m response_PguuidService_CreateProductReturnPartial_0) XXX_ResponseBody() interface{} {
	return m.CreateProductReturnPartialRow
}

type response_PguuidService_CreateUserReturnAll_0 struct {
	*CreateUserReturnAllResponse
}

func (m response_PguuidService_CreateUserReturnAll_0) XXX_ResponseBody() interface{} {
	return m.User
}

type response_PguuidService_CreateUserReturnPartial_0 struct {
	*CreateUserReturnPartialResponse
}

func (m response_PguuidService_CreateUserReturnPartial_0) XXX_ResponseBody() interface{} {
	return m.CreateUserReturnPartialRow
}

var (
	pattern_PguuidService_CreateProduct_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0}, []string{"product"}, ""))

	pattern_PguuidService_CreateProductReturnAll_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0}, []string{"product-return-all"}, ""))

	pattern_PguuidService_CreateProductReturnPartial_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0}, []string{"product-return-partial"}, ""))

	pattern_PguuidService_CreateUser_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0}, []string{"user"}, ""))

	pattern_PguuidService_CreateUserReturnAll_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0}, []string{"user-return-all"}, ""))

	pattern_PguuidService_CreateUserReturnPartial_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0}, []string{"user-return-partial"}, ""))
)

var (
	forward_PguuidService_CreateProduct_0 = runtime.ForwardResponseMessage

	forward_PguuidService_CreateProductReturnAll_0 = runtime.ForwardResponseMessage

	forward_PguuidService_CreateProductReturnPartial_0 = runtime.ForwardResponseMessage

	forward_PguuidService_CreateUser_0 = runtime.ForwardResponseMessage

	forward_PguuidService_CreateUserReturnAll_0 = runtime.ForwardResponseMessage

	forward_PguuidService_CreateUserReturnPartial_0 = runtime.ForwardResponseMessage
)
