// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: books/v1/books.proto

package v1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Author struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorId      int32                  `protobuf:"varint,1,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Author) Reset() {
	*x = Author{}
	mi := &file_books_v1_books_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Author) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Author) ProtoMessage() {}

func (x *Author) ProtoReflect() protoreflect.Message {
	mi := &file_books_v1_books_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Author.ProtoReflect.Descriptor instead.
func (*Author) Descriptor() ([]byte, []int) {
	return file_books_v1_books_proto_rawDescGZIP(), []int{0}
}

func (x *Author) GetAuthorId() int32 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *Author) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Book struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        int32                  `protobuf:"varint,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	AuthorId      int32                  `protobuf:"varint,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Isbn          string                 `protobuf:"bytes,3,opt,name=isbn,proto3" json:"isbn,omitempty"`
	BookType      string                 `protobuf:"bytes,4,opt,name=book_type,json=bookType,proto3" json:"book_type,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Year          int32                  `protobuf:"varint,6,opt,name=year,proto3" json:"year,omitempty"`
	Available     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=available,proto3" json:"available,omitempty"`
	Tags          []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Book) Reset() {
	*x = Book{}
	mi := &file_books_v1_books_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_books_v1_books_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_books_v1_books_proto_rawDescGZIP(), []int{1}
}

func (x *Book) GetBookId() int32 {
	if x != nil {
		return x.BookId
	}
	return 0
}

func (x *Book) GetAuthorId() int32 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *Book) GetIsbn() string {
	if x != nil {
		return x.Isbn
	}
	return ""
}

func (x *Book) GetBookType() string {
	if x != nil {
		return x.BookType
	}
	return ""
}

func (x *Book) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Book) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Book) GetAvailable() *timestamppb.Timestamp {
	if x != nil {
		return x.Available
	}
	return nil
}

func (x *Book) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type BookType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookType) Reset() {
	*x = BookType{}
	mi := &file_books_v1_books_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookType) ProtoMessage() {}

func (x *BookType) ProtoReflect() protoreflect.Message {
	mi := &file_books_v1_books_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookType.ProtoReflect.Descriptor instead.
func (*BookType) Descriptor() ([]byte, []int) {
	return file_books_v1_books_proto_rawDescGZIP(), []int{2}
}

type BooksByTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dollar_1      []string               `protobuf:"bytes,1,rep,name=dollar_1,json=dollar1,proto3" json:"dollar_1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BooksByTagsRequest) Reset() {
	*x = BooksByTagsRequest{}
	mi := &file_books_v1_books_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BooksByTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BooksByTagsRequest) ProtoMessage() {}

func (x *BooksByTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_books_v1_books_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BooksByTagsRequest.ProtoReflect.Descriptor instead.
func (*BooksByTagsRequest) Descriptor() ([]byte, []int) {
	return file_books_v1_books_proto_rawDescGZIP(), []int{3}
}

func (x *BooksByTagsRequest) GetDollar_1() []string {
	if x != nil {
		return x.Dollar_1
	}
	return nil
}

type BooksByTagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*BooksByTagsRow      `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BooksByTagsResponse) Reset() {
	*x = BooksByTagsResponse{}
	mi := &file_books_v1_books_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BooksByTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BooksByTagsResponse) ProtoMessage() {}

func (x *BooksByTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_books_v1_books_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BooksByTagsResponse.ProtoReflect.Descriptor instead.
func (*BooksByTagsResponse) Descriptor() ([]byte, []int) {
	return file_books_v1_books_proto_rawDescGZIP(), []int{4}
}

func (x *BooksByTagsResponse) GetList() []*BooksByTagsRow {
	if x != nil {
		return x.List
	}
	return nil
}

type BooksByTagsRow struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	BookId        int32                   `protobuf:"varint,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	Title         string                  `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Name          *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Isbn          string                  `protobuf:"bytes,4,opt,name=isbn,proto3" json:"isbn,omitempty"`
	Tags          []string                `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BooksByTagsRow) Reset() {
	*x = BooksByTagsRow{}
	mi := &file_books_v1_books_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BooksByTagsRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BooksByTagsRow) ProtoMessage() {}

func (x *BooksByTagsRow) ProtoReflect() protoreflect.Message {
	mi := &file_books_v1_books_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BooksByTagsRow.ProtoReflect.Descriptor instead.
func (*BooksByTagsRow) Descriptor() ([]byte, []int) {
	return file_books_v1_books_proto_rawDescGZIP(), []int{5}
}

func (x *BooksByTagsRow) GetBookId() int32 {
	if x != nil {
		return x.BookId
	}
	return 0
}

func (x *BooksByTagsRow) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BooksByTagsRow) GetName() *wrapperspb.StringValue {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *BooksByTagsRow) GetIsbn() string {
	if x != nil {
		return x.Isbn
	}
	return ""
}

func (x *BooksByTagsRow) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type BooksByTitleYearRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Year          int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BooksByTitleYearRequest) Reset() {
	*x = BooksByTitleYearRequest{}
	mi := &file_books_v1_books_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BooksByTitleYearRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BooksByTitleYearRequest) ProtoMessage() {}

func (x *BooksByTitleYearRequest) ProtoReflect() protoreflect.Message {
	mi := &file_books_v1_books_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BooksByTitleYearRequest.ProtoReflect.Descriptor instead.
func (*BooksByTitleYearRequest) Descriptor() ([]byte, []int) {
	return file_books_v1_books_proto_rawDescGZIP(), []int{6}
}

func (x *BooksByTitleYearRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BooksByTitleYearRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type BooksByTitleYearResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*Book                `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BooksByTitleYearResponse) Reset() {
	*x = BooksByTitleYearResponse{}
	mi := &file_books_v1_books_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BooksByTitleYearResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BooksByTitleYearResponse) ProtoMessage() {}

func (x *BooksByTitleYearResponse) ProtoReflect() protoreflect.Message {
	mi := &file_books_v1_books_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BooksByTitleYearResponse.ProtoReflect.Descriptor instead.
func (*BooksByTitleYearResponse) Descriptor() ([]byte, []int) {
	return file_books_v1_books_proto_rawDescGZIP(), []int{7}
}

func (x *BooksByTitleYearResponse) GetList() []*Book {
	if x != nil {
		return x.List
	}
	return nil
}

type CreateAuthorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAuthorRequest) Reset() {
	*x = CreateAuthorRequest{}
	mi := &file_books_v1_books_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAuthorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAuthorRequest) ProtoMessage() {}

func (x *CreateAuthorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_books_v1_books_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAuthorRequest.ProtoReflect.Descriptor instead.
func (*CreateAuthorRequest) Descriptor() ([]byte, []int) {
	return file_books_v1_books_proto_rawDescGZIP(), []int{8}
}

func (x *CreateAuthorRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateAuthorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Author        *Author                `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAuthorResponse) Reset() {
	*x = CreateAuthorResponse{}
	mi := &file_books_v1_books_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAuthorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAuthorResponse) ProtoMessage() {}

func (x *CreateAuthorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_books_v1_books_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAuthorResponse.ProtoReflect.Descriptor instead.
func (*CreateAuthorResponse) Descriptor() ([]byte, []int) {
	return file_books_v1_books_proto_rawDescGZIP(), []int{9}
}

func (x *CreateAuthorResponse) GetAuthor() *Author {
	if x != nil {
		return x.Author
	}
	return nil
}

type CreateBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorId      int32                  `protobuf:"varint,1,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Isbn          string                 `protobuf:"bytes,2,opt,name=isbn,proto3" json:"isbn,omitempty"`
	BookType      string                 `protobuf:"bytes,3,opt,name=book_type,json=bookType,proto3" json:"book_type,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Year          int32                  `protobuf:"varint,5,opt,name=year,proto3" json:"year,omitempty"`
	Available     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=available,proto3" json:"available,omitempty"`
	Tags          []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookRequest) Reset() {
	*x = CreateBookRequest{}
	mi := &file_books_v1_books_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookRequest) ProtoMessage() {}

func (x *CreateBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_books_v1_books_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookRequest.ProtoReflect.Descriptor instead.
func (*CreateBookRequest) Descriptor() ([]byte, []int) {
	return file_books_v1_books_proto_rawDescGZIP(), []int{10}
}

func (x *CreateBookRequest) GetAuthorId() int32 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *CreateBookRequest) GetIsbn() string {
	if x != nil {
		return x.Isbn
	}
	return ""
}

func (x *CreateBookRequest) GetBookType() string {
	if x != nil {
		return x.BookType
	}
	return ""
}

func (x *CreateBookRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateBookRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *CreateBookRequest) GetAvailable() *timestamppb.Timestamp {
	if x != nil {
		return x.Available
	}
	return nil
}

func (x *CreateBookRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type CreateBookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Book          *Book                  `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookResponse) Reset() {
	*x = CreateBookResponse{}
	mi := &file_books_v1_books_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookResponse) ProtoMessage() {}

func (x *CreateBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_books_v1_books_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookResponse.ProtoReflect.Descriptor instead.
func (*CreateBookResponse) Descriptor() ([]byte, []int) {
	return file_books_v1_books_proto_rawDescGZIP(), []int{11}
}

func (x *CreateBookResponse) GetBook() *Book {
	if x != nil {
		return x.Book
	}
	return nil
}

type DeleteBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        int32                  `protobuf:"varint,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBookRequest) Reset() {
	*x = DeleteBookRequest{}
	mi := &file_books_v1_books_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBookRequest) ProtoMessage() {}

func (x *DeleteBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_books_v1_books_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBookRequest.ProtoReflect.Descriptor instead.
func (*DeleteBookRequest) Descriptor() ([]byte, []int) {
	return file_books_v1_books_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteBookRequest) GetBookId() int32 {
	if x != nil {
		return x.BookId
	}
	return 0
}

type DeleteBookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBookResponse) Reset() {
	*x = DeleteBookResponse{}
	mi := &file_books_v1_books_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBookResponse) ProtoMessage() {}

func (x *DeleteBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_books_v1_books_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBookResponse.ProtoReflect.Descriptor instead.
func (*DeleteBookResponse) Descriptor() ([]byte, []int) {
	return file_books_v1_books_proto_rawDescGZIP(), []int{13}
}

type GetAuthorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorId      int32                  `protobuf:"varint,1,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthorRequest) Reset() {
	*x = GetAuthorRequest{}
	mi := &file_books_v1_books_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthorRequest) ProtoMessage() {}

func (x *GetAuthorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_books_v1_books_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthorRequest.ProtoReflect.Descriptor instead.
func (*GetAuthorRequest) Descriptor() ([]byte, []int) {
	return file_books_v1_books_proto_rawDescGZIP(), []int{14}
}

func (x *GetAuthorRequest) GetAuthorId() int32 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

type GetAuthorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Author        *Author                `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthorResponse) Reset() {
	*x = GetAuthorResponse{}
	mi := &file_books_v1_books_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthorResponse) ProtoMessage() {}

func (x *GetAuthorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_books_v1_books_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthorResponse.ProtoReflect.Descriptor instead.
func (*GetAuthorResponse) Descriptor() ([]byte, []int) {
	return file_books_v1_books_proto_rawDescGZIP(), []int{15}
}

func (x *GetAuthorResponse) GetAuthor() *Author {
	if x != nil {
		return x.Author
	}
	return nil
}

type GetBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        int32                  `protobuf:"varint,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookRequest) Reset() {
	*x = GetBookRequest{}
	mi := &file_books_v1_books_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookRequest) ProtoMessage() {}

func (x *GetBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_books_v1_books_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookRequest.ProtoReflect.Descriptor instead.
func (*GetBookRequest) Descriptor() ([]byte, []int) {
	return file_books_v1_books_proto_rawDescGZIP(), []int{16}
}

func (x *GetBookRequest) GetBookId() int32 {
	if x != nil {
		return x.BookId
	}
	return 0
}

type GetBookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Book          *Book                  `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookResponse) Reset() {
	*x = GetBookResponse{}
	mi := &file_books_v1_books_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookResponse) ProtoMessage() {}

func (x *GetBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_books_v1_books_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookResponse.ProtoReflect.Descriptor instead.
func (*GetBookResponse) Descriptor() ([]byte, []int) {
	return file_books_v1_books_proto_rawDescGZIP(), []int{17}
}

func (x *GetBookResponse) GetBook() *Book {
	if x != nil {
		return x.Book
	}
	return nil
}

type NullBookType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookType      string                 `protobuf:"bytes,1,opt,name=book_type,json=bookType,proto3" json:"book_type,omitempty"`
	Valid         bool                   `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NullBookType) Reset() {
	*x = NullBookType{}
	mi := &file_books_v1_books_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NullBookType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullBookType) ProtoMessage() {}

func (x *NullBookType) ProtoReflect() protoreflect.Message {
	mi := &file_books_v1_books_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullBookType.ProtoReflect.Descriptor instead.
func (*NullBookType) Descriptor() ([]byte, []int) {
	return file_books_v1_books_proto_rawDescGZIP(), []int{18}
}

func (x *NullBookType) GetBookType() string {
	if x != nil {
		return x.BookType
	}
	return ""
}

func (x *NullBookType) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

type UpdateBookISBNRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Isbn          string                 `protobuf:"bytes,1,opt,name=isbn,proto3" json:"isbn,omitempty"`
	BookId        int32                  `protobuf:"varint,2,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBookISBNRequest) Reset() {
	*x = UpdateBookISBNRequest{}
	mi := &file_books_v1_books_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBookISBNRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBookISBNRequest) ProtoMessage() {}

func (x *UpdateBookISBNRequest) ProtoReflect() protoreflect.Message {
	mi := &file_books_v1_books_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBookISBNRequest.ProtoReflect.Descriptor instead.
func (*UpdateBookISBNRequest) Descriptor() ([]byte, []int) {
	return file_books_v1_books_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateBookISBNRequest) GetIsbn() string {
	if x != nil {
		return x.Isbn
	}
	return ""
}

func (x *UpdateBookISBNRequest) GetBookId() int32 {
	if x != nil {
		return x.BookId
	}
	return 0
}

type UpdateBookISBNResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBookISBNResponse) Reset() {
	*x = UpdateBookISBNResponse{}
	mi := &file_books_v1_books_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBookISBNResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBookISBNResponse) ProtoMessage() {}

func (x *UpdateBookISBNResponse) ProtoReflect() protoreflect.Message {
	mi := &file_books_v1_books_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBookISBNResponse.ProtoReflect.Descriptor instead.
func (*UpdateBookISBNResponse) Descriptor() ([]byte, []int) {
	return file_books_v1_books_proto_rawDescGZIP(), []int{20}
}

type UpdateBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Tags          []string               `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	BookType      string                 `protobuf:"bytes,3,opt,name=book_type,json=bookType,proto3" json:"book_type,omitempty"`
	BookId        int32                  `protobuf:"varint,4,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBookRequest) Reset() {
	*x = UpdateBookRequest{}
	mi := &file_books_v1_books_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBookRequest) ProtoMessage() {}

func (x *UpdateBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_books_v1_books_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBookRequest.ProtoReflect.Descriptor instead.
func (*UpdateBookRequest) Descriptor() ([]byte, []int) {
	return file_books_v1_books_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateBookRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateBookRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UpdateBookRequest) GetBookType() string {
	if x != nil {
		return x.BookType
	}
	return ""
}

func (x *UpdateBookRequest) GetBookId() int32 {
	if x != nil {
		return x.BookId
	}
	return 0
}

type UpdateBookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBookResponse) Reset() {
	*x = UpdateBookResponse{}
	mi := &file_books_v1_books_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBookResponse) ProtoMessage() {}

func (x *UpdateBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_books_v1_books_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBookResponse.ProtoReflect.Descriptor instead.
func (*UpdateBookResponse) Descriptor() ([]byte, []int) {
	return file_books_v1_books_proto_rawDescGZIP(), []int{22}
}

var File_books_v1_books_proto protoreflect.FileDescriptor

const file_books_v1_books_proto_rawDesc = "" +
	"\n" +
	"\x14books/v1/books.proto\x12\bbooks.v1\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"9\n" +
	"\x06Author\x12\x1b\n" +
	"\tauthor_id\x18\x01 \x01(\x05R\bauthorId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xe5\x01\n" +
	"\x04Book\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\x05R\x06bookId\x12\x1b\n" +
	"\tauthor_id\x18\x02 \x01(\x05R\bauthorId\x12\x12\n" +
	"\x04isbn\x18\x03 \x01(\tR\x04isbn\x12\x1b\n" +
	"\tbook_type\x18\x04 \x01(\tR\bbookType\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x12\n" +
	"\x04year\x18\x06 \x01(\x05R\x04year\x128\n" +
	"\tavailable\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tavailable\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\"\n" +
	"\n" +
	"\bBookType\"/\n" +
	"\x12BooksByTagsRequest\x12\x19\n" +
	"\bdollar_1\x18\x01 \x03(\tR\adollar1\"C\n" +
	"\x13BooksByTagsResponse\x12,\n" +
	"\x04list\x18\x01 \x03(\v2\x18.books.v1.BooksByTagsRowR\x04list\"\x99\x01\n" +
	"\x0eBooksByTagsRow\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\x05R\x06bookId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x120\n" +
	"\x04name\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\x04name\x12\x12\n" +
	"\x04isbn\x18\x04 \x01(\tR\x04isbn\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\"C\n" +
	"\x17BooksByTitleYearRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\">\n" +
	"\x18BooksByTitleYearResponse\x12\"\n" +
	"\x04list\x18\x01 \x03(\v2\x0e.books.v1.BookR\x04list\")\n" +
	"\x13CreateAuthorRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"@\n" +
	"\x14CreateAuthorResponse\x12(\n" +
	"\x06author\x18\x01 \x01(\v2\x10.books.v1.AuthorR\x06author\"\xd9\x01\n" +
	"\x11CreateBookRequest\x12\x1b\n" +
	"\tauthor_id\x18\x01 \x01(\x05R\bauthorId\x12\x12\n" +
	"\x04isbn\x18\x02 \x01(\tR\x04isbn\x12\x1b\n" +
	"\tbook_type\x18\x03 \x01(\tR\bbookType\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x12\n" +
	"\x04year\x18\x05 \x01(\x05R\x04year\x128\n" +
	"\tavailable\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tavailable\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\"8\n" +
	"\x12CreateBookResponse\x12\"\n" +
	"\x04book\x18\x01 \x01(\v2\x0e.books.v1.BookR\x04book\",\n" +
	"\x11DeleteBookRequest\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\x05R\x06bookId\"\x14\n" +
	"\x12DeleteBookResponse\"/\n" +
	"\x10GetAuthorRequest\x12\x1b\n" +
	"\tauthor_id\x18\x01 \x01(\x05R\bauthorId\"=\n" +
	"\x11GetAuthorResponse\x12(\n" +
	"\x06author\x18\x01 \x01(\v2\x10.books.v1.AuthorR\x06author\")\n" +
	"\x0eGetBookRequest\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\x05R\x06bookId\"5\n" +
	"\x0fGetBookResponse\x12\"\n" +
	"\x04book\x18\x01 \x01(\v2\x0e.books.v1.BookR\x04book\"A\n" +
	"\fNullBookType\x12\x1b\n" +
	"\tbook_type\x18\x01 \x01(\tR\bbookType\x12\x14\n" +
	"\x05valid\x18\x02 \x01(\bR\x05valid\"D\n" +
	"\x15UpdateBookISBNRequest\x12\x12\n" +
	"\x04isbn\x18\x01 \x01(\tR\x04isbn\x12\x17\n" +
	"\abook_id\x18\x02 \x01(\x05R\x06bookId\"\x18\n" +
	"\x16UpdateBookISBNResponse\"s\n" +
	"\x11UpdateBookRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04tags\x18\x02 \x03(\tR\x04tags\x12\x1b\n" +
	"\tbook_type\x18\x03 \x01(\tR\bbookType\x12\x17\n" +
	"\abook_id\x18\x04 \x01(\x05R\x06bookId\"\x14\n" +
	"\x12UpdateBookResponse2\xcd\a\n" +
	"\fBooksService\x12r\n" +
	"\vBooksByTags\x12\x1c.books.v1.BooksByTagsRequest\x1a\x1d.books.v1.BooksByTagsResponse\"&\x82\xd3\xe4\x93\x02 :\bdollar_1b\x04list\"\x0e/books-by-tags\x12o\n" +
	"\x10BooksByTitleYear\x12!.books.v1.BooksByTitleYearRequest\x1a\".books.v1.BooksByTitleYearResponse\"\x14\x82\xd3\xe4\x93\x02\x0eb\x04list\x12\x06/books\x12j\n" +
	"\fCreateAuthor\x12\x1d.books.v1.CreateAuthorRequest\x1a\x1e.books.v1.CreateAuthorResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*b\x06author\"\b/authors\x12`\n" +
	"\n" +
	"CreateBook\x12\x1b.books.v1.CreateBookRequest\x1a\x1c.books.v1.CreateBookResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*b\x04book\"\x06/books\x12a\n" +
	"\n" +
	"DeleteBook\x12\x1b.books.v1.DeleteBookRequest\x1a\x1c.books.v1.DeleteBookResponse\"\x18\x82\xd3\xe4\x93\x02\x12*\x10/books/{book_id}\x12j\n" +
	"\tGetAuthor\x12\x1a.books.v1.GetAuthorRequest\x1a\x1b.books.v1.GetAuthorResponse\"$\x82\xd3\xe4\x93\x02\x1eb\x06author\x12\x14/authors/{author_id}\x12^\n" +
	"\aGetBook\x12\x18.books.v1.GetBookRequest\x1a\x19.books.v1.GetBookResponse\"\x1e\x82\xd3\xe4\x93\x02\x18b\x04book\x12\x10/books/{book_id}\x12d\n" +
	"\n" +
	"UpdateBook\x12\x1b.books.v1.UpdateBookRequest\x1a\x1c.books.v1.UpdateBookResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\x1a\x10/books/{book_id}\x12u\n" +
	"\x0eUpdateBookISBN\x12\x1f.books.v1.UpdateBookISBNRequest\x1a .books.v1.UpdateBookISBNResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*2\x15/books/{book_id}/isbnB\xee\x01\x92A\xd3\x01\x12\xd0\x01\n" +
	"\bbooktest\x12\x83\x01Boilerplate code generated by **sqlc-grpc**. Modify _proto/*.proto_ files then run `buf generate` to change the services interface.\"9\n" +
	"\tsqlc-grpc\x12,https://github.com/walterwanderley/sqlc-grpc2\x031.0Z\x15booktest/api/books/v1b\x06proto3"

var (
	file_books_v1_books_proto_rawDescOnce sync.Once
	file_books_v1_books_proto_rawDescData []byte
)

func file_books_v1_books_proto_rawDescGZIP() []byte {
	file_books_v1_books_proto_rawDescOnce.Do(func() {
		file_books_v1_books_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_books_v1_books_proto_rawDesc), len(file_books_v1_books_proto_rawDesc)))
	})
	return file_books_v1_books_proto_rawDescData
}

var file_books_v1_books_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_books_v1_books_proto_goTypes = []any{
	(*Author)(nil),                   // 0: books.v1.Author
	(*Book)(nil),                     // 1: books.v1.Book
	(*BookType)(nil),                 // 2: books.v1.BookType
	(*BooksByTagsRequest)(nil),       // 3: books.v1.BooksByTagsRequest
	(*BooksByTagsResponse)(nil),      // 4: books.v1.BooksByTagsResponse
	(*BooksByTagsRow)(nil),           // 5: books.v1.BooksByTagsRow
	(*BooksByTitleYearRequest)(nil),  // 6: books.v1.BooksByTitleYearRequest
	(*BooksByTitleYearResponse)(nil), // 7: books.v1.BooksByTitleYearResponse
	(*CreateAuthorRequest)(nil),      // 8: books.v1.CreateAuthorRequest
	(*CreateAuthorResponse)(nil),     // 9: books.v1.CreateAuthorResponse
	(*CreateBookRequest)(nil),        // 10: books.v1.CreateBookRequest
	(*CreateBookResponse)(nil),       // 11: books.v1.CreateBookResponse
	(*DeleteBookRequest)(nil),        // 12: books.v1.DeleteBookRequest
	(*DeleteBookResponse)(nil),       // 13: books.v1.DeleteBookResponse
	(*GetAuthorRequest)(nil),         // 14: books.v1.GetAuthorRequest
	(*GetAuthorResponse)(nil),        // 15: books.v1.GetAuthorResponse
	(*GetBookRequest)(nil),           // 16: books.v1.GetBookRequest
	(*GetBookResponse)(nil),          // 17: books.v1.GetBookResponse
	(*NullBookType)(nil),             // 18: books.v1.NullBookType
	(*UpdateBookISBNRequest)(nil),    // 19: books.v1.UpdateBookISBNRequest
	(*UpdateBookISBNResponse)(nil),   // 20: books.v1.UpdateBookISBNResponse
	(*UpdateBookRequest)(nil),        // 21: books.v1.UpdateBookRequest
	(*UpdateBookResponse)(nil),       // 22: books.v1.UpdateBookResponse
	(*timestamppb.Timestamp)(nil),    // 23: google.protobuf.Timestamp
	(*wrapperspb.StringValue)(nil),   // 24: google.protobuf.StringValue
}
var file_books_v1_books_proto_depIdxs = []int32{
	23, // 0: books.v1.Book.available:type_name -> google.protobuf.Timestamp
	5,  // 1: books.v1.BooksByTagsResponse.list:type_name -> books.v1.BooksByTagsRow
	24, // 2: books.v1.BooksByTagsRow.name:type_name -> google.protobuf.StringValue
	1,  // 3: books.v1.BooksByTitleYearResponse.list:type_name -> books.v1.Book
	0,  // 4: books.v1.CreateAuthorResponse.author:type_name -> books.v1.Author
	23, // 5: books.v1.CreateBookRequest.available:type_name -> google.protobuf.Timestamp
	1,  // 6: books.v1.CreateBookResponse.book:type_name -> books.v1.Book
	0,  // 7: books.v1.GetAuthorResponse.author:type_name -> books.v1.Author
	1,  // 8: books.v1.GetBookResponse.book:type_name -> books.v1.Book
	3,  // 9: books.v1.BooksService.BooksByTags:input_type -> books.v1.BooksByTagsRequest
	6,  // 10: books.v1.BooksService.BooksByTitleYear:input_type -> books.v1.BooksByTitleYearRequest
	8,  // 11: books.v1.BooksService.CreateAuthor:input_type -> books.v1.CreateAuthorRequest
	10, // 12: books.v1.BooksService.CreateBook:input_type -> books.v1.CreateBookRequest
	12, // 13: books.v1.BooksService.DeleteBook:input_type -> books.v1.DeleteBookRequest
	14, // 14: books.v1.BooksService.GetAuthor:input_type -> books.v1.GetAuthorRequest
	16, // 15: books.v1.BooksService.GetBook:input_type -> books.v1.GetBookRequest
	21, // 16: books.v1.BooksService.UpdateBook:input_type -> books.v1.UpdateBookRequest
	19, // 17: books.v1.BooksService.UpdateBookISBN:input_type -> books.v1.UpdateBookISBNRequest
	4,  // 18: books.v1.BooksService.BooksByTags:output_type -> books.v1.BooksByTagsResponse
	7,  // 19: books.v1.BooksService.BooksByTitleYear:output_type -> books.v1.BooksByTitleYearResponse
	9,  // 20: books.v1.BooksService.CreateAuthor:output_type -> books.v1.CreateAuthorResponse
	11, // 21: books.v1.BooksService.CreateBook:output_type -> books.v1.CreateBookResponse
	13, // 22: books.v1.BooksService.DeleteBook:output_type -> books.v1.DeleteBookResponse
	15, // 23: books.v1.BooksService.GetAuthor:output_type -> books.v1.GetAuthorResponse
	17, // 24: books.v1.BooksService.GetBook:output_type -> books.v1.GetBookResponse
	22, // 25: books.v1.BooksService.UpdateBook:output_type -> books.v1.UpdateBookResponse
	20, // 26: books.v1.BooksService.UpdateBookISBN:output_type -> books.v1.UpdateBookISBNResponse
	18, // [18:27] is the sub-list for method output_type
	9,  // [9:18] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_books_v1_books_proto_init() }
func file_books_v1_books_proto_init() {
	if File_books_v1_books_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_books_v1_books_proto_rawDesc), len(file_books_v1_books_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_books_v1_books_proto_goTypes,
		DependencyIndexes: file_books_v1_books_proto_depIdxs,
		MessageInfos:      file_books_v1_books_proto_msgTypes,
	}.Build()
	File_books_v1_books_proto = out.File
	file_books_v1_books_proto_goTypes = nil
	file_books_v1_books_proto_depIdxs = nil
}
