// Code generated by sqlc-grpc (https://github.com/walterwanderley/sqlc-grpc). DO NOT EDIT.

package books

import (
	"google.golang.org/protobuf/types/known/timestamppb"
	"google.golang.org/protobuf/types/known/wrapperspb"

	pb "booktest/api/books/v1"
)

func toAuthor(in Author) *pb.Author {

	out := new(pb.Author)
	out.AuthorId = in.AuthorID
	out.Name = in.Name
	return out
}

func toBook(in Book) *pb.Book {

	out := new(pb.Book)
	out.BookId = in.BookID
	out.AuthorId = in.AuthorID
	out.Isbn = in.Isbn
	out.BookType = string(in.BookType)
	out.Title = in.Title
	out.Year = in.Year
	out.Available = timestamppb.New(in.Available)
	out.Tags = in.Tags
	return out
}

func toBooksByTagsRow(in BooksByTagsRow) *pb.BooksByTagsRow {

	out := new(pb.BooksByTagsRow)
	out.BookId = in.BookID
	out.Title = in.Title
	if in.Name.Valid {
		out.Name = wrapperspb.String(in.Name.String)
	}
	out.Isbn = in.Isbn
	out.Tags = in.Tags
	return out
}
