// Code generated by sqlc-grpc (https://github.com/walterwanderley/sqlc-grpc).

package books

import (
	"go.uber.org/zap"

	pb "booktest/proto/books"
)

// NewService is a constructor of a pb.BooksServiceServer implementation.
// Use this function to customize the server by adding middlewares to it.
func NewService(logger *zap.Logger, querier *Queries) pb.BooksServiceServer {
	return &Service{logger: logger, querier: querier}
}
