// Code generated by sqlc-grpc (https://github.com/walterwanderley/sqlc-grpc).

package books

import (
	"database/sql"

	pb "booktest/api/books/v1"
)

// NewService is a constructor of a pb.BooksServiceServer implementation.
// Use this function to customize the server by adding middlewares to it.
func NewService(querier *Queries, db *sql.DB) pb.BooksServiceServer {
	return &Service{querier: querier}
}
