// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package books

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BooksServiceClient is the client API for BooksService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BooksServiceClient interface {
	BooksByTags(ctx context.Context, in *BooksByTagsParams, opts ...grpc.CallOption) (*BooksByTagsResponse, error)
	BooksByTitleYear(ctx context.Context, in *BooksByTitleYearParams, opts ...grpc.CallOption) (*BooksByTitleYearResponse, error)
	CreateAuthor(ctx context.Context, in *CreateAuthorParams, opts ...grpc.CallOption) (*Author, error)
	CreateBook(ctx context.Context, in *CreateBookParams, opts ...grpc.CallOption) (*Book, error)
	DeleteBook(ctx context.Context, in *DeleteBookParams, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetAuthor(ctx context.Context, in *GetAuthorParams, opts ...grpc.CallOption) (*Author, error)
	GetBook(ctx context.Context, in *GetBookParams, opts ...grpc.CallOption) (*Book, error)
	UpdateBook(ctx context.Context, in *UpdateBookParams, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateBookISBN(ctx context.Context, in *UpdateBookISBNParams, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type booksServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBooksServiceClient(cc grpc.ClientConnInterface) BooksServiceClient {
	return &booksServiceClient{cc}
}

func (c *booksServiceClient) BooksByTags(ctx context.Context, in *BooksByTagsParams, opts ...grpc.CallOption) (*BooksByTagsResponse, error) {
	out := new(BooksByTagsResponse)
	err := c.cc.Invoke(ctx, "/books.BooksService/BooksByTags", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *booksServiceClient) BooksByTitleYear(ctx context.Context, in *BooksByTitleYearParams, opts ...grpc.CallOption) (*BooksByTitleYearResponse, error) {
	out := new(BooksByTitleYearResponse)
	err := c.cc.Invoke(ctx, "/books.BooksService/BooksByTitleYear", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *booksServiceClient) CreateAuthor(ctx context.Context, in *CreateAuthorParams, opts ...grpc.CallOption) (*Author, error) {
	out := new(Author)
	err := c.cc.Invoke(ctx, "/books.BooksService/CreateAuthor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *booksServiceClient) CreateBook(ctx context.Context, in *CreateBookParams, opts ...grpc.CallOption) (*Book, error) {
	out := new(Book)
	err := c.cc.Invoke(ctx, "/books.BooksService/CreateBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *booksServiceClient) DeleteBook(ctx context.Context, in *DeleteBookParams, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/books.BooksService/DeleteBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *booksServiceClient) GetAuthor(ctx context.Context, in *GetAuthorParams, opts ...grpc.CallOption) (*Author, error) {
	out := new(Author)
	err := c.cc.Invoke(ctx, "/books.BooksService/GetAuthor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *booksServiceClient) GetBook(ctx context.Context, in *GetBookParams, opts ...grpc.CallOption) (*Book, error) {
	out := new(Book)
	err := c.cc.Invoke(ctx, "/books.BooksService/GetBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *booksServiceClient) UpdateBook(ctx context.Context, in *UpdateBookParams, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/books.BooksService/UpdateBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *booksServiceClient) UpdateBookISBN(ctx context.Context, in *UpdateBookISBNParams, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/books.BooksService/UpdateBookISBN", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BooksServiceServer is the server API for BooksService service.
// All implementations must embed UnimplementedBooksServiceServer
// for forward compatibility
type BooksServiceServer interface {
	BooksByTags(context.Context, *BooksByTagsParams) (*BooksByTagsResponse, error)
	BooksByTitleYear(context.Context, *BooksByTitleYearParams) (*BooksByTitleYearResponse, error)
	CreateAuthor(context.Context, *CreateAuthorParams) (*Author, error)
	CreateBook(context.Context, *CreateBookParams) (*Book, error)
	DeleteBook(context.Context, *DeleteBookParams) (*emptypb.Empty, error)
	GetAuthor(context.Context, *GetAuthorParams) (*Author, error)
	GetBook(context.Context, *GetBookParams) (*Book, error)
	UpdateBook(context.Context, *UpdateBookParams) (*emptypb.Empty, error)
	UpdateBookISBN(context.Context, *UpdateBookISBNParams) (*emptypb.Empty, error)
	mustEmbedUnimplementedBooksServiceServer()
}

// UnimplementedBooksServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBooksServiceServer struct {
}

func (UnimplementedBooksServiceServer) BooksByTags(context.Context, *BooksByTagsParams) (*BooksByTagsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BooksByTags not implemented")
}
func (UnimplementedBooksServiceServer) BooksByTitleYear(context.Context, *BooksByTitleYearParams) (*BooksByTitleYearResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BooksByTitleYear not implemented")
}
func (UnimplementedBooksServiceServer) CreateAuthor(context.Context, *CreateAuthorParams) (*Author, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAuthor not implemented")
}
func (UnimplementedBooksServiceServer) CreateBook(context.Context, *CreateBookParams) (*Book, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBook not implemented")
}
func (UnimplementedBooksServiceServer) DeleteBook(context.Context, *DeleteBookParams) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBook not implemented")
}
func (UnimplementedBooksServiceServer) GetAuthor(context.Context, *GetAuthorParams) (*Author, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAuthor not implemented")
}
func (UnimplementedBooksServiceServer) GetBook(context.Context, *GetBookParams) (*Book, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBook not implemented")
}
func (UnimplementedBooksServiceServer) UpdateBook(context.Context, *UpdateBookParams) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBook not implemented")
}
func (UnimplementedBooksServiceServer) UpdateBookISBN(context.Context, *UpdateBookISBNParams) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBookISBN not implemented")
}
func (UnimplementedBooksServiceServer) mustEmbedUnimplementedBooksServiceServer() {}

// UnsafeBooksServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BooksServiceServer will
// result in compilation errors.
type UnsafeBooksServiceServer interface {
	mustEmbedUnimplementedBooksServiceServer()
}

func RegisterBooksServiceServer(s grpc.ServiceRegistrar, srv BooksServiceServer) {
	s.RegisterService(&BooksService_ServiceDesc, srv)
}

func _BooksService_BooksByTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BooksByTagsParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BooksServiceServer).BooksByTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/books.BooksService/BooksByTags",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BooksServiceServer).BooksByTags(ctx, req.(*BooksByTagsParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _BooksService_BooksByTitleYear_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BooksByTitleYearParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BooksServiceServer).BooksByTitleYear(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/books.BooksService/BooksByTitleYear",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BooksServiceServer).BooksByTitleYear(ctx, req.(*BooksByTitleYearParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _BooksService_CreateAuthor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAuthorParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BooksServiceServer).CreateAuthor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/books.BooksService/CreateAuthor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BooksServiceServer).CreateAuthor(ctx, req.(*CreateAuthorParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _BooksService_CreateBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBookParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BooksServiceServer).CreateBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/books.BooksService/CreateBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BooksServiceServer).CreateBook(ctx, req.(*CreateBookParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _BooksService_DeleteBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBookParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BooksServiceServer).DeleteBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/books.BooksService/DeleteBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BooksServiceServer).DeleteBook(ctx, req.(*DeleteBookParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _BooksService_GetAuthor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuthorParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BooksServiceServer).GetAuthor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/books.BooksService/GetAuthor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BooksServiceServer).GetAuthor(ctx, req.(*GetAuthorParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _BooksService_GetBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBookParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BooksServiceServer).GetBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/books.BooksService/GetBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BooksServiceServer).GetBook(ctx, req.(*GetBookParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _BooksService_UpdateBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBookParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BooksServiceServer).UpdateBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/books.BooksService/UpdateBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BooksServiceServer).UpdateBook(ctx, req.(*UpdateBookParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _BooksService_UpdateBookISBN_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBookISBNParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BooksServiceServer).UpdateBookISBN(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/books.BooksService/UpdateBookISBN",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BooksServiceServer).UpdateBookISBN(ctx, req.(*UpdateBookISBNParams))
	}
	return interceptor(ctx, in, info, handler)
}

// BooksService_ServiceDesc is the grpc.ServiceDesc for BooksService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BooksService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "books.BooksService",
	HandlerType: (*BooksServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BooksByTags",
			Handler:    _BooksService_BooksByTags_Handler,
		},
		{
			MethodName: "BooksByTitleYear",
			Handler:    _BooksService_BooksByTitleYear_Handler,
		},
		{
			MethodName: "CreateAuthor",
			Handler:    _BooksService_CreateAuthor_Handler,
		},
		{
			MethodName: "CreateBook",
			Handler:    _BooksService_CreateBook_Handler,
		},
		{
			MethodName: "DeleteBook",
			Handler:    _BooksService_DeleteBook_Handler,
		},
		{
			MethodName: "GetAuthor",
			Handler:    _BooksService_GetAuthor_Handler,
		},
		{
			MethodName: "GetBook",
			Handler:    _BooksService_GetBook_Handler,
		},
		{
			MethodName: "UpdateBook",
			Handler:    _BooksService_UpdateBook_Handler,
		},
		{
			MethodName: "UpdateBookISBN",
			Handler:    _BooksService_UpdateBookISBN_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "books.proto",
}
