// Code generated by sqlc-grpc (https://github.com/walterwanderley/sqlc-grpc). DO NOT EDIT.

package main

import (
	"github.com/jackc/pgx/v5/pgxpool"
	"google.golang.org/grpc"

	pb_googleuuid "uuidcheck/api/googleuuid/v1"
	pb_pguuid "uuidcheck/api/pguuid/v1"
	"uuidcheck/internal/server"
	app_googleuuid "uuidcheck/store/googleuuid"
	app_pguuid "uuidcheck/store/pguuid"
)

func registerServer(db *pgxpool.Pool) server.RegisterServer {
	return func(grpcServer *grpc.Server) {
		pb_googleuuid.RegisterGoogleuuidServiceServer(grpcServer, app_googleuuid.NewService(app_googleuuid.New(db), db))
		pb_pguuid.RegisterPguuidServiceServer(grpcServer, app_pguuid.NewService(app_pguuid.New(db), db))

	}
}

func registerHandlers() []server.RegisterHandlerFromEndpoint {
	var handlers []server.RegisterHandlerFromEndpoint

	handlers = append(handlers, pb_googleuuid.RegisterGoogleuuidServiceHandlerFromEndpoint)
	handlers = append(handlers, pb_pguuid.RegisterPguuidServiceHandlerFromEndpoint)

	return handlers
}
