// Code generated by sqlc-grpc (https://github.com/walterwanderley/sqlc-grpc). DO NOT EDIT.

package main

import (
	"database/sql"

	"google.golang.org/grpc"

	pb_books "booktest/api/books/v1"
	app_books "booktest/internal/books"
	"booktest/internal/server"
)

func registerServer(db *sql.DB) server.RegisterServer {
	return func(grpcServer *grpc.Server) {
		pb_books.RegisterBooksServiceServer(grpcServer, app_books.NewService(app_books.New(db), db))

	}
}

func registerHandlers() []server.RegisterHandlerFromEndpoint {
	var handlers []server.RegisterHandlerFromEndpoint

	handlers = append(handlers, pb_books.RegisterBooksServiceHandlerFromEndpoint)

	return handlers
}
