// Code generated by sqlc-grpc (https://github.com/walterwanderley/sqlc-grpc).

package googleuuid

import (
	"github.com/jackc/pgx/v5/pgxpool"

	pb "uuidcheck/api/googleuuid/v1"
)

// NewService is a constructor of a pb.GoogleuuidServiceServer implementation.
// Use this function to customize the server by adding middlewares to it.
func NewService(querier *Queries, db *pgxpool.Pool) pb.GoogleuuidServiceServer {
	return &Service{querier: querier}
}
